
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David Santiago Carrillo
 */
public class Ventana extends javax.swing.JFrame {
    private List<Videojuegos> videojuegosList;
    private Ordenamiento ordenamiento;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Autor: David Carrillo");
        videojuegosList = new ArrayList<>();
        ordenamiento = new Ordenamiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        cjFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cjListado = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(" David Santiago Carrillo Salamanca");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 310, 340, 11);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btIngresar.setText("Agregar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btIngresar);
        btIngresar.setBounds(180, 120, 120, 23);

        jLabel2.setText("Nombre del Videojuego:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 150, 20);

        jLabel3.setText("Categoria:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 100, 20);

        jLabel4.setText("Fecha de lanzamiento:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 130, 20);
        jPanel1.add(cjNombre);
        cjNombre.setBounds(150, 30, 150, 22);
        jPanel1.add(cjIdentificacion);
        cjIdentificacion.setBounds(150, 60, 150, 22);
        jPanel1.add(cjFechaNacimiento);
        cjFechaNacimiento.setBounds(150, 90, 150, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Videojuegos");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 0, 250, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 310, 160);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        cjListado.setColumns(20);
        cjListado.setRows(5);
        jScrollPane1.setViewportView(cjListado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 290, 120);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Videojuegos agregados");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 10, 250, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 10, 310, 160);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(530, 300, 100, 23);

        setSize(new java.awt.Dimension(666, 185));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ingresar();
    }

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        salir();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjFechaNacimiento;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextArea cjListado;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration

    private void ingresar() {
        String nombre = cjNombre.getText();
        String categoria = cjIdentificacion.getText();
        int ano = Integer.parseInt(cjFechaNacimiento.getText());

        Videojuegos nuevoVideojuego = new Videojuegos(nombre, categoria, ano);
        videojuegosList.add(nuevoVideojuego);

        cjNombre.setText("");
        cjIdentificacion.setText("");
        cjFechaNacimiento.setText("");

        JOptionPane.showMessageDialog(this, "Videojuego ingresado", "ATENCIÓN", JOptionPane.INFORMATION_MESSAGE);
        actualizaListado();
    }


    private void atender() {
        JOptionPane.showMessageDialog(this, "Atender", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
        this.actualizaListado();
    }
    private void actualizaListado() {
        StringBuilder listado = new StringBuilder();
        for (Videojuegos videojuego : videojuegosList) {
            listado.append(videojuego.toString()).append("\n");
        }
        cjListado.setText(listado.toString());
    }

    private void salir() {
        System.exit(0);
    }
}