import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utilidad.MetodosOrdenamiento;

public class Ventana extends javax.swing.JFrame {
    private List<Comparable> videojuegosList;
    private MetodosOrdenamiento metodosOrdenamiento;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Autor: David Carrillo");
        videojuegosList = new ArrayList<>();
        metodosOrdenamiento = new MetodosOrdenamiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        cjFechaLanzamiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cjListado = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        btBubbleSort = new javax.swing.JButton();
        btQuickSort = new javax.swing.JButton();
        btInsertSort = new javax.swing.JButton();
        btBucketSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(" David Santiago Carrillo Salamanca");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 310, 340, 11);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btIngresar.setText("Agregar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btIngresar);
        btIngresar.setBounds(180, 120, 120, 23);

        jLabel2.setText("Nombre del Videojuego:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 150, 20);

        jLabel3.setText("Categoría:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 100, 20);

        jLabel4.setText("Fecha de lanzamiento:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 130, 20);
        jPanel1.add(cjNombre);
        cjNombre.setBounds(150, 30, 150, 22);
        jPanel1.add(cjIdentificacion);
        cjIdentificacion.setBounds(150, 60, 150, 22);
        jPanel1.add(cjFechaLanzamiento);
        cjFechaLanzamiento.setBounds(150, 90, 150, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 310, 160);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        cjListado.setColumns(20);
        cjListado.setRows(5);
        jScrollPane1.setViewportView(cjListado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 290, 120);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Videojuegos agregados");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 10, 250, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 10, 310, 160);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(530, 300, 100, 23);

        btBubbleSort.setText("Bubble Sort");
        btBubbleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBubbleSortActionPerformed(evt);
            }
        });
        getContentPane().add(btBubbleSort);
        btBubbleSort.setBounds(10, 190, 120, 23);

        btQuickSort.setText("Quick Sort");
        btQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuickSortActionPerformed(evt);
            }
        });
        getContentPane().add(btQuickSort);
        btQuickSort.setBounds(150, 190, 120, 23);

        btInsertSort.setText("Insert Sort");
        btInsertSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertSortActionPerformed(evt);
            }
        });
        getContentPane().add(btInsertSort);
        btInsertSort.setBounds(290, 190, 120, 23);

        btBucketSort.setText("Bucket Sort");
        btBucketSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBucketSortActionPerformed(evt);
            }
        });
        getContentPane().add(btBucketSort);
        btBucketSort.setBounds(430, 190, 120, 23);

        setSize(new java.awt.Dimension(666, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {
        ingresar();
    }

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {
        salir();
    }

    private void btBubbleSortActionPerformed(java.awt.event.ActionEvent evt) {
        bubbleSort();
    }

    private void btQuickSortActionPerformed(java.awt.event.ActionEvent evt) {
        quickSort();
    }

    private void btInsertSortActionPerformed(java.awt.event.ActionEvent evt) {
        insertSort();
    }

    private void btBucketSortActionPerformed(java.awt.event.ActionEvent evt) {
        bucketSort();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private void ingresar() {
        String nombre = cjNombre.getText();
        String categoria = cjIdentificacion.getText();
        int ano = Integer.parseInt(cjFechaLanzamiento.getText());

        Videojuego nVide = new Videojuego(nombre, categoria, ano);
        videojuegosList.add(nVide);

        cjNombre.setText("");
        cjIdentificacion.setText("");
        cjFechaLanzamiento.setText("");

        actualizarListado();
    }

    private void actualizarListado() {
        cjListado.setText("");
        for (Comparable videojuego : videojuegosList) {
            cjListado.append(videojuego.toString() + "\n");
        }
    }

    private void bubbleSort() {
        metodosOrdenamiento.bubbleSortList(videojuegosList);
        metodosOrdenamiento.imprimirBubbleSortList(videojuegosList);
    }

    private void quickSort() {
        metodosOrdenamiento.quickSortList(videojuegosList, 0, videojuegosList.size() - 1);
        metodosOrdenamiento.imprimirQuickSortList(videojuegosList);
    }

    private void insertSort() {
        metodosOrdenamiento.insertSortList(videojuegosList);
        metodosOrdenamiento.imprimirInsertSortList(videojuegosList);
    }

    private void bucketSort() {
        metodosOrdenamiento.bucketSortList(videojuegosList);
        metodosOrdenamiento.imprimirBucketSortList(videojuegosList);
    }

    private void salir() {
        System.exit(0);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btBubbleSort;
    private javax.swing.JButton btBucketSort;
    private javax.swing.JButton btInsertSort;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btQuickSort;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjFechaLanzamiento;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextArea cjListado;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
